### PR TITLE
Feature/controllers

### PR DESCRIPTION
**Pull request by vitrineofcode**

### CODE REVIEW

**Review by nebstech — APPROVED** [review]

**Review by nebstech — DISMISSED** [review]
conflicts

**Comment by Fekinox** [comment]
This update will add in basic persistence features-- game logs will automatically be created when a race ends, and for each bet that has been placed, it will update the corresponding user by both changing their balance and recording the bet in their bet log.

**Review by Fekinox — APPROVED** [review]
Taken care of in latest commit

**Review by Fekinox — APPROVED** [review]
Taken care of in latest commits

**Pull request merged**
